In [1]:
import torch
import torch.distributions as dist

/opt/anaconda3/envs/deeplearning/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
# Lets create a Bernoulli distribution

bernoulli = dist.Bernoulli(torch.tensor([0.5]))

# Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])


In [3]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.48100000619888306
Variance: 0.24988888204097748


In [4]:
# Lets create a Normal distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(normal.sample())

tensor([-1.2189])
tensor([-1.2254])
tensor([2.4767])
tensor([1.5589])
tensor([0.5397])
tensor([-0.8216])
tensor([-1.0785])
tensor([0.6656])
tensor([0.8621])
tensor([0.8876])


In [5]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: -0.007625647820532322
Variance: 1.0005438327789307
